### ISSUE TITLE
Tailwind 4 compatibility

### ISSUE THREAD

**Issue by techniq** [techniq/layerchart#388]
Tailwind 4 now declares CSS variables WITH a color function such as:

```css
@import 'tailwindcss';
@source '../node_modules/layerchart/**/*.{svelte,js}';

@theme {
    --color-primary: hsl(257.4075 100% 50%);
    --color-surface-100: hsl(180 100% 100%);
    --color-surface-200: hsl(0 0% 94.902%);
    --color-surface-300: hsl(180 1.9608% 90%);
    --color-surface-content: hsl(215 27.907% 16.8627%);
}
```

which means they are now used via `var(--color-primary)` instead of `hsl(var(--color-primary))` when referenced directly, such as for the [default series color](https://github.com/techniq/layerchart/blob/main/packages/layerchart/src/lib/components/charts/AreaChart.svelte#L71).  Both TW3 and TW4 work the same when used via a class, such as `fill-primary` or `stroke-surface-content`.

Declaring with the color function is much nicer as this means all color functions (`hsl()`, `rgb()`, `oklch()`, ...) can be used out of the box without needing to know the original color space.

In LayerChart 2.0 we will default to Tailwind 4 usage, but until then, you can explicitly provide the default series color using:

```svelte
<AreaChart
  {data}
  x="date"
  y="value"
  series={[{ key: 'value', color: 'var(--color-primary)' }]}
/>
```

See this [repo](https://github.com/techniq/layerchart-tailwind4-example) for an example.

**Comment by techniq** [comment]
More context:

It comes down to knowing how the `--color-primary` (and others) are set.

In [Tailwind 3](https://v3.tailwindcss.com/docs/customizing-colors#using-css-variables), you would declare it as:

```css
:root {
  --color-primary: 200 100% 50%
}
```

and then declare in your `tailwind.config.js` as

```js
module.exports = {
  theme: {
    colors: {
      // Using modern `hsl`
      primary: 'hsl(var(--color-primary))'
    }
  }
}
```

In [Tailwind 4](https://tailwindcss.com/docs/colors#customizing-your-colors), you define them in your CSS file only (in  @theme declaration WITH the color space function (`rgb()`, `hsl()`, `oklch()`, etc)

```css
@import "tailwindcss";
@theme {
  --color-primary: hsl(200 100% 50%);
}
```

this means `var(--color-primary)` will resolve as `200 100% 50%` on TW3 and needs to be wrapped in `hsl(var(--color-primary))`, but in TW4 it's just `var(--color-primary)` which resolves to `hsl(200 100% 50%)`

98% of the time LayerChart uses tailwind colors via classes (`stroke-primary`, `fill-surface-100`, etc) with the one big exception being setting a default series color for the simplified charts
Hopefully I can find a solution that works for TW3 and TW4 as I'd rather not break TW3 usage (just yet) to support TW4
