### ISSUE TITLE
Gradient components

### ISSUE THREAD

**Issue by techniq** [techniq/layerchart#4]
- Use css variables, similar to [tailwind](https://tailwindcss.com/docs/background-image#linear-gradients)
- visx
  - https://github.com/airbnb/visx/tree/master/packages/visx-gradient
  - https://airbnb.io/visx/gradients
- https://stackoverflow.com/a/55269126/191902

```html
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" class="shape">
  <defs>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
      </linearGradient>
  </defs>
  <g>
    <polygon class="gradient-bg" points="0,0 100,0 0,66" />
  </g>
</svg>
```
```css
.shape {
  width:500px;
  height:200px;
}

.shape .gradient-bg {
  fill: url(#header-shape-gradient) #fff;
}

#header-shape-gradient {
  --color-stop: #f12c06;
  --color-bot: #faed34;
}
```
